### ISSUE TITLE
Provided blitz++ does not compile with recent g++

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/LNAplusplus#5]
```
/bin/bash ../libtool  --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H   -I.. -I..     -MT globals.lo -MD -MP -MF .deps/globals.Tpo -c -o globals.lo `test -f '../src/globals.cpp' || echo './'`../src/globals.cpp
libtool: compile:  c++ -DHAVE_CONFIG_H -I.. -I.. -MT globals.lo -MD -MP -MF .deps/globals.Tpo -c ../src/globals.cpp -o globals.o
In file included from ../blitz/array/asexpr.cc:38:0,
                 from ../blitz/array.cc:9,
                 from ../blitz/array-impl.h:2559,
                 from ../blitz/array.h:37,
                 from ../src/globals.cpp:12:
../blitz/array/expr.h: In instantiation of 'class blitz::_bz_ArrayExpr<blitz::FastTV2Iterator<int, 2> >':
../blitz/array/asexpr.h:224:10:   required from 'struct blitz::BzBinaryExprResult<blitz::Subtract, blitz::TinyVector<int, 2>, std::complex<long double> >'
../blitz/array/ops.h:127:1:   required by substitution of 'template<class T> typename blitz::BzBinaryExprResult<blitz::Subtract, T, std::complex<long double> >::T_result blitz::operator-(const blitz::ETBase<T>&, std::complex<long double>) [with T = blitz::TinyVector<int, 2>]'
../blitz/tinymat2.h:197:21:   required from here
../blitz/array/expr.h:111:44: error: invalid use of incomplete type 'blitz::_bz_ArrayExpr<blitz::FastTV2Iterator<int, 2> >::T_expr {aka class blitz::FastTV2Iterator<int, 2>}'
     typedef _bz_typename T_expr::T_numtype T_numtype;
                                            ^~~~~~~~~
[ many more errors omitted ]
```

Blitz++ has moved to https://github.com/blitzpp/blitz 

Need to update documentation and test with newer versions

**Comment by dweindl** [comment]
Works with blitz-1.0.1
